version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes
hooks:
  BeforeInstall:
    - location: remove-before-install.sh
      timeout: 30
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 30
