version: "2.1"
orbs:
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
  aws-s3: circleci/aws-s3@2.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  deploy-step1:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: zip -r app.zip . -i ./*
      - run: mkdir deploy
      - run: mv app.zip deploy
      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./deploy/*
          to: "s3://nuspam-static/backend/"
      - aws-s3/copy:
          from: ./deploy/*
          to: "s3://nuspam-static/backend/"

workflows:
  deploy_application:
    jobs:
      - deploy-step1
      - aws-code-deploy/deploy:
          requires:
            - deploy-step1
          application-name: nuspam-api
          bundle-bucket: nuspam-static
          bundle-key: app.zip
          deployment-group: api-server
          service-role-arn: arn:aws:iam::737382971423:role/Role_for_codedeploy
          filters:
            branches:
              only: main
